language: csharp
dist: bionic
mono: none
services:
  - docker
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
deploy:
  provider: script
  script: bash ./scripts/travis-deploy.sh
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+(\.[0-9])?$
notifications:
  email:
    on_success: never
    on_failure: always