version: '3'
services: 
    mongodb:
        image: mongo:latest
        container_name: mongodb
        expose:
            - 27017
        ports: 
            - "27017:27017"
        networks:
            - bot_network
        volumes:
        - db-data:/data/db
        - mongo-config:/data/configdb
    watchman-web:
        container_name: watchman
        depends_on:
            - mongodb
        build: .
        ports:
            - "8080:80"
        networks:
            - bot_network
        volumes:
            - ./appsettings.Development.json:/app/appsettings.json
            - /etc/localtime:/etc/localtime:ro
            - ./logs:/app/logs
volumes:
    db-data:
    mongo-config:
networks:
    bot_network:
