version: '3'
services: 
    watchman-web:
        build: .
        ports:
            - "8080:80"
        restart: "unless-stopped"
        volumes:
            - ./appsettings.json:/app/appsettings.json
            - /etc/localtime:/etc/localtime:ro